/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package twitteranalysisapp;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Mia
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCrawling = new javax.swing.JMenu();
        jMenuPraprocess = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuPembobotan = new javax.swing.JMenu();
        jMenuKlasifikasi = new javax.swing.JMenu();
        jMenuSentiment = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TwitterAnalysisHome");
        setBackground(new java.awt.Color(102, 204, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 481));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        label1.setBackground(new java.awt.Color(204, 204, 204));
        label1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        label1.setText("Klasifikasi Emosi  Dan Analisis Sentiment");
        label1.setBounds(170, 10, 258, 19);
        jDesktopPane1.add(label1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label2.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        label2.setText("Akun Media Sosial Jurusan Teknik Informatika");
        label2.setBounds(160, 40, 288, 19);
        jDesktopPane1.add(label2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label3.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        label3.setText("Menggunakan Algoritma Synesketch");
        label3.setBounds(190, 70, 226, 20);
        jDesktopPane1.add(label3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 490));

        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N

        jMenuCrawling.setText("Crawling");
        jMenuCrawling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCrawlingMouseClicked(evt);
            }
        });
        jMenuCrawling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCrawlingActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuCrawling);

        jMenuPraprocess.setText("Praprocess");
        jMenuPraprocess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPraprocessMouseClicked(evt);
            }
        });
        jMenuPraprocess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPraprocessActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Bentuk Model");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuPraprocess.add(jMenuItem1);

        jMenuItem2.setText("Testing");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuPraprocess.add(jMenuItem2);

        jMenuBar1.add(jMenuPraprocess);

        jMenuPembobotan.setText("Pembobotan");
        jMenuPembobotan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPembobotanMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuPembobotan);

        jMenuKlasifikasi.setText("Klasifikasi");
        jMenuKlasifikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuKlasifikasiMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuKlasifikasi);

        jMenuSentiment.setText("Sentiment");
        jMenuSentiment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSentimentMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSentiment);

        jMenuHelp.setText("Help");
        jMenuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHelpMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHelp);

        jMenuAbout.setBackground(new java.awt.Color(0, 153, 255));
        jMenuAbout.setText("About");
        jMenuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAbout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCrawlingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCrawlingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCrawlingActionPerformed

    private void jMenuPraprocessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPraprocessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuPraprocessActionPerformed

    private void jMenuCrawlingMouseClicked(java.awt.event.MouseEvent evt) {
       CrawlingData cr= new CrawlingData();
       cr.show();
       this.dispose();
    }

    private void jMenuPraprocessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPraprocessMouseClicked
        // TODO add your handling code here:
//        new Preprocess().show();
//        this.dispose();
    }//GEN-LAST:event_jMenuPraprocessMouseClicked

    private void jMenuHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHelpMouseClicked
        // TODO add your handling code here:
       new Help().show();
        this.dispose();
    }//GEN-LAST:event_jMenuHelpMouseClicked

    private void jMenuKlasifikasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuKlasifikasiMouseClicked
        // TODO add your handling code here:
        new klasifikasi().show();
        this.dispose();
        
    }//GEN-LAST:event_jMenuKlasifikasiMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new TextProcessing().show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuPembobotanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPembobotanMouseClicked
        // TODO add your handling code here:
        new Pembobotan().show();
        this.dispose();
    }//GEN-LAST:event_jMenuPembobotanMouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAboutMouseClicked
        // TODO add your handling code here:
        new About().show();
        this.dispose();
    }//GEN-LAST:event_jMenuAboutMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new TextProcessingUji().show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuSentimentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSentimentMouseClicked
        // TODO add your handling code here:
        new sentimentForm().show();
        this.dispose();
    }//GEN-LAST:event_jMenuSentimentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        BufferedReader br = null;
        
        String CurrentLine;
        try {
            // 1. Buat objek dari kelas buffered reader
            br = new BufferedReader(new FileReader("D:\\inputtext.txt"));
            
            // 2. Baca Setiap Line menggunakan methode readline
            while ((CurrentLine = br.readLine()) != null) {
               // System.out.println(CurrentLine);
            }
            
            // 3. close stream setiap habis baca/tulia
            br.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                    SwingUtilities.updateComponentTreeUI(new FormUtama());
                } catch (Exception e) {
                }
                new FormUtama().setVisible(true);
//                import_data ambil = new import_data();
//                try {
//                    ambil.importexcel();
//                } catch (SQLException ex) {
//                    Logger.getLogger(CrawmingData.class.getName()).log(Level.SEVERE, null, ex);
//                }
                 
            }
        });
//       
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCrawling;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuKlasifikasi;
    private javax.swing.JMenu jMenuPembobotan;
    private javax.swing.JMenu jMenuPraprocess;
    private javax.swing.JMenu jMenuSentiment;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
