/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package twitteranalysisapp;

import com.mysql.jdbc.PreparedStatement;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mia
 */
public class TextProcessing extends javax.swing.JFrame {

    /**
     * Creates new form textprocessing
     */
    int no;
    String twit, hasilcase, hasilnormalisasi, anotasi, potong, kalimat, data, hasil;
    private String[] kata;
    private String[] str;
    private String sCurrentLine;
    private DefaultTableModel model;
    int k = 0;

    public TextProcessing() {
        initComponents();
        this.setLocationRelativeTo(null);
        //model buat tabel
        model = new DefaultTableModel();
        jTable2.setModel(model);
        model.addColumn("Id Tweet");
        model.addColumn("Tweet");
        model.addColumn("Kategori Emosi");
        lihatdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonNormalisasi = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButtonKataEmosi = new javax.swing.JButton();
        jButtonStopword = new javax.swing.JButton();
        jButtonPraprocess = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TwitterAnalysisPraprocess");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setToolTipText("");

        jButtonNormalisasi.setText("Normalisasi");
        jButtonNormalisasi.setToolTipText("");
        jButtonNormalisasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNormalisasiActionPerformed(evt);
            }
        });

        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButtonKataEmosi.setText("Kata Emosi");
        jButtonKataEmosi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKataEmosiActionPerformed(evt);
            }
        });

        jButtonStopword.setText("Stopword");
        jButtonStopword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonStopwordMouseClicked(evt);
            }
        });
        jButtonStopword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopwordActionPerformed(evt);
            }
        });

        jButtonPraprocess.setText("Praproses Data");
        jButtonPraprocess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPraprocessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNormalisasi, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jButtonStopword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKataEmosi, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPraprocess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonNormalisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStopword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonKataEmosi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPraprocess, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNormalisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNormalisasiActionPerformed
//        try {
//            normalisasi();
//        } catch (IOException ex) {
//            Logger.getLogger(TextProcessing.class.getName()).log(Level.SEVERE, null, ex);
//        }
        lihathasilnormalisasi();
    }//GEN-LAST:event_jButtonNormalisasiActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        new FormUtama().show();
        this.dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonKataEmosiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKataEmosiActionPerformed
       // cariKata();
        lihathasilcleaning();
        //TokenKata();
    }//GEN-LAST:event_jButtonKataEmosiActionPerformed

    private void jButtonStopwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopwordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStopwordMouseClicked

    private void jButtonStopwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopwordActionPerformed
        // TODO add your handling code here:
//        try {
//            ProsesStopword();
//        } catch (IOException ex) {
//            Logger.getLogger(TextProcessing.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
        lihathasilstopword();
    }//GEN-LAST:event_jButtonStopwordActionPerformed

    private void jButtonPraprocessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPraprocessActionPerformed
        // TODO add your handling code here:
        lihathasiltoken();
       // TokenKata();
    }//GEN-LAST:event_jButtonPraprocessActionPerformed

    void lihatdata() {
        String id, tweet, anotasi;

        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        Connection tampildata;
        try {
            tampildata = koneksi.getKoneksi();
            Statement st1 = tampildata.createStatement();
            String sql_tampildata = "select * from datafilter";
            ResultSet rr2 = st1.executeQuery(sql_tampildata);
            while (rr2.next()) {
                Object[] o = new Object[3];
                id = rr2.getString("id_tweet");
                tweet = rr2.getString("tweet");
                anotasi = rr2.getString("anotator");
                o[0] = id;
                o[1] = tweet;
                o[2] = anotasi;
                model.addRow(o);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TextProcessing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void lihathasilnormalisasi() {
        String id2, tweet2, anotasi2;

        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        Connection tampilstopword;
        try {
            tampilstopword = koneksi.getKoneksi();
            Statement st1 = tampilstopword.createStatement();
            String sql_tampilstopword = "select * from datatweet";
            ResultSet rr2 = st1.executeQuery(sql_tampilstopword);
            while (rr2.next()) {
                Object[] o = new Object[3];
                id2 = rr2.getString("id_tweet");
                tweet2 = rr2.getString("tweet");
                anotasi2 = rr2.getString("anotator");
                o[0] = id2;
                o[1] = tweet2;
                o[2] = anotasi2;
                model.addRow(o);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TextProcessing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    void lihathasilstopword(){
        
        String id2, tweet2, anotasi2;

        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        Connection tampilstopword;
        try {
            tampilstopword = koneksi.getKoneksi();
            Statement st1 = tampilstopword.createStatement();
            String sql_tampilstopword = "select * from datahasilstopword";
            ResultSet rr2 = st1.executeQuery(sql_tampilstopword);
            while (rr2.next()) {
                Object[] o = new Object[3];
                id2 = rr2.getString("id_tweet");
                tweet2 = rr2.getString("tweet");
                anotasi2 = rr2.getString("anotasi");
                o[0] = id2;
                o[1] = tweet2;
                o[2] = anotasi2;
                model.addRow(o);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TextProcessing.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    
    void lihathasilcleaning(){
        String id2, tweet2, anotasi2;

        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        Connection tampilstopword;
        try {
            tampilstopword = koneksi.getKoneksi();
            Statement st1 = tampilstopword.createStatement();
            String sql_tampilstopword = "select * from datacleaning";
            ResultSet rr2 = st1.executeQuery(sql_tampilstopword);
            while (rr2.next()) {
                Object[] o = new Object[3];
                id2 = rr2.getString("id_tweet");
                tweet2 = rr2.getString("tweet");
                anotasi2 = rr2.getString("anotasi");
                o[0] = id2;
                o[1] = tweet2;
                o[2] = anotasi2;
                model.addRow(o);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TextProcessing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void lihathasiltoken(){
        String idtweet, kata, anotasi;

        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        Connection tampilstopword;
        try {
            tampilstopword = koneksi.getKoneksi();
            Statement st1 = tampilstopword.createStatement();
            String sql_tampilstopword = "select * from token";
            ResultSet rr2 = st1.executeQuery(sql_tampilstopword);
            while (rr2.next()) {
                Object[] o = new Object[3];
                idtweet = rr2.getString("id_tweet");
                kata = rr2.getString("kata");
                anotasi = rr2.getString("anotator");
                o[0] = idtweet;
                o[1] = kata;
                o[2] = anotasi;
                model.addRow(o);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TextProcessing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void normalisasi() throws IOException {
        Connection cnormmalisasi;
        try {
            cnormmalisasi= koneksi.getKoneksi();
            Statement s1 = cnormmalisasi.createStatement();
            String sql = "select id_tweet, tweet, anotator from datafilter ";
            ResultSet rr2 = s1.executeQuery(sql);
            while (rr2.next()) {
                int x = 1;
                String nomor = rr2.getString("id_tweet");
                twit = rr2.getString("tweet");
                anotasi = rr2.getString("anotator");
                hasilcase = clear(twit);
                //System.out.println(hasilcase);
                //simpan(nomor, twit, anotasi);    
                StringBuilder builder = new StringBuilder();
                builder.append("");
                kata = hasilcase.split(" ");

                for (int i = 0; i < kata.length; i++) {
                    Connection cConvertEmo = koneksi.getKoneksi();
                    Statement sConvertEmo = cConvertEmo.createStatement();
                    String sqlConvertEmo = "select kata from kamusemoticon where emoticon = '"+ kata[i]+ "'";
                    ResultSet rst = sConvertEmo.executeQuery(sqlConvertEmo);
                    while (rst.next()) {
                      String kataemo = rst.getString("kata");
                      kata[i] = kataemo;
                      //System.out.println(kata[i]);
                    }
                     // builder.append(kata[i]).append(" ");
                }

                
                for (int i = 0; i < kata.length; i++) {
                    Connection cConvertEmo = koneksi.getKoneksi();
                    Statement sConvertEmo = cConvertEmo.createStatement();
                    String sqlConvertEmo = "select kata2 from katapadanan where kata1 = '"+ kata[i]+ "'";
                    ResultSet rst = sConvertEmo.executeQuery(sqlConvertEmo);
                    while (rst.next()) {
                      String kataganti = rst.getString("kata2");
                      kata[i] = kataganti;
                      //System.out.println(kata[i]);
                    }
                      builder.append(kata[i]).append(" ");
                }
                
                String hasilConvertKata = builder.toString();
                System.out.println(hasilConvertKata);
                System.out.println("=================================");
                //simpan2(nomor, hasilConvertKata, anotasi);
            }

        } catch (SQLException ex) {
            System.out.print("proses gagal");
            Logger.getLogger(TextProcessing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static String removeSymbol(String text) {
        text = text.replaceAll("@\\w+|#\\w+|\\brt\\b", "")
                .replaceAll("\\n", " ")
                .replaceAll(" +", " ")
                .replaceAll("[0-9]", " ");
        return text;
    }

    public static String removeUrl(String text) {
        String urlPattern = "((https?|ftp|gopher|telnet|file|Unsure|http):((//)|(\\\\))+[\\w\\d:#@%/;$()~_?\\+-=\\\\\\.&]*)";
        Pattern p = Pattern.compile(urlPattern, Pattern.CASE_INSENSITIVE);
        Matcher m = p.matcher(text);
        int i = 0;
        while (m.find()) {
            text = text.replaceAll(m.group(i), "").trim();
            i++;
        }
        return text;
    }

    public static String removeExtraSpaces(String text) {
        text = text.trim().replaceAll("\\s+", " ");
        return text;
    }

    public static String clear(String text) {
        text = TextProcessing.removeSymbol(text);
        text = TextProcessing.removeUrl(text);
        text = TextProcessing.removeExtraSpaces(text);

        return text;
    }
   
    void simpan2(String no, String hasilcase, String anotasi) {
        Connection c3;
        try {
            c3 = koneksi.getKoneksi();
            Statement s3 = c3.createStatement();
            String sql3 = "insert into datatweet (id_tweet, tweet, anotator) values (?,?,?)";
            PreparedStatement o3 = (PreparedStatement) c3.prepareStatement(sql3);
            o3.setString(1, no);
            o3.setString(2, hasilcase);
            o3.setString(3, anotasi);
            o3.executeUpdate();
        } catch (SQLException ex) {
            System.out.println("Terjadi kesalahan");
            Logger.getLogger(TextProcessing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void ProsesStopword() throws IOException {
        Connection c4;
        try {
            c4 = koneksi.getKoneksi();
            Statement s4 = c4.createStatement();
            String sql4 = "select id_tweet, tweet, anotator from datatweet ";
            ResultSet rr2 = s4.executeQuery(sql4);
            while (rr2.next()) {

                String nomor = rr2.getString("id_tweet");
                String tweet = rr2.getString("tweet");
                String anotasii = rr2.getString("anotator");
                //String delims="[ \t.,;() ]+";
                String delims = "[\\W\\d]+";
                //StringBuilder builder = new StringBuilder();
                kata = tweet.trim().split(delims);
                String proses = stopword(kata);

                //simpan3(nomor,proses,anotasii);
            }
        } catch (SQLException ex) {
            System.out.print("proses gagal");
            Logger.getLogger(TextProcessing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String stopword(String[] str) throws IOException {
        try {
            Connection c2 = koneksi.getKoneksi();
        } catch (SQLException ex) {
            Logger.getLogger(TextProcessing.class.getName()).log(Level.SEVERE, null, ex);
        }

        String delims = "[\\W\\d]+";
        // String delims="[\\W]+"; 

        ArrayList<String> wordsList = new ArrayList<String>();
        String sCurrentLine;
        int k = 0;
        String[] stopwords = new String[2000];

        FileReader fr = null;
        fr = new FileReader("D:\\liststopword_id.txt");
        BufferedReader br = new BufferedReader(fr);

        while ((sCurrentLine = br.readLine()) != null) {
            stopwords[k] = sCurrentLine;
            k++;
        }

        StringBuilder builder = new StringBuilder();
        builder.append("");

        wordsList.addAll(Arrays.asList(str));
        for (int i = 0; i < wordsList.size(); i++) {
            for (int j = 0; j < k; j++) {
                if (stopwords[j].contains(wordsList.get(i))) {
                    wordsList.remove(i);
                    break;
                }
            }
        }

        builder.append(wordsList);
        kalimat = builder.toString().replaceAll(delims, "  ");
        System.out.println(kalimat);

        return kalimat;

    }

    void simpan3(String no, String hasilcase, String anotasi) {
        Connection c8;
        try {
            c8 = koneksi.getKoneksi();
            Statement s8 = c8.createStatement();
            String sql8 = "insert into datahasilstopword (id_tweet, tweet, anotasi) values (?,?,?)";
            PreparedStatement o3 = (PreparedStatement) c8.prepareStatement(sql8);
            o3.setString(1, no);
            o3.setString(2, hasilcase);
            o3.setString(3, anotasi);
            o3.executeUpdate();
        } catch (SQLException ex) {
            System.out.println("Terjadi kesalahan");
            Logger.getLogger(Preprocess.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void cariKata() {
        Connection c9;
        try {
            c9 = koneksi.getKoneksi();
            Statement s9 = c9.createStatement();
            String sql9 = "select id_tweet, tweet, anotasi from datahasilstopword ";
            ResultSet rr2 = s9.executeQuery(sql9);
            while (rr2.next()) {

                String nomor = rr2.getString("id_tweet");
                String tweet = rr2.getString("tweet");
                String anotasii = rr2.getString("anotasi");
                String delims = "[ \t.,;()]+";
                StringBuilder builder = new StringBuilder();
                kata = tweet.trim().split(delims);
                String hasil = cekKata(kata);
              //  simpan4(nomor, hasil, anotasii); 
            }
        } catch (SQLException ex) {
            System.out.print("proses gagal");
            Logger.getLogger(Preprocess.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static String cekKata(String[] str) throws SQLException {
        StringBuilder builder = new StringBuilder();
        builder.append("");
        String delims = "[ \t.,;()]+";
        ArrayList<String> wordsList = new ArrayList<String>();
        wordsList.addAll(Arrays.asList(str));
        String sql = "select * from kataemosi ";
        // where kata ='"+ str +"'
        Statement st = koneksi.getKoneksi().createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            String hsl = rs.getString("kata");
            // System.out.println(hsl);
            for (int i = 0; i < wordsList.size(); i++) {
                if (hsl.equals(wordsList.get(i))) {
                    builder.append(wordsList.get(i) + " ");
                    //System.out.println(wordsList.get(i))
                }
            }
        }
//                builder.append(wordsList);
        String kataemosi = builder.toString().replaceAll(delims, " ");
        System.out.println(kataemosi);

        return kataemosi;
    }

    void simpan4(String no, String tweet, String anotasi) {
        Connection c9;
        try {
            c9 = koneksi.getKoneksi();
            Statement s9 = c9.createStatement();
            String sql9 = "insert into datacleaning (id_tweet, tweet, anotasi) values (?,?,?)";
            PreparedStatement o9 = (PreparedStatement) c9.prepareStatement(sql9);
            o9.setString(1, no);
            o9.setString(2, tweet);
            o9.setString(3, anotasi);
            o9.executeUpdate();

        } catch (SQLException ex) {
            System.out.println("Terjadi kesalahan");
            Logger.getLogger(Preprocess.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void TokenKata() {
        try {
            Connection c10 = koneksi.getKoneksi();
            Statement s10 = c10.createStatement();
            String sql10 = "select id_tweet, tweet, anotasi from datacleaning ";
            ResultSet rr2 = s10.executeQuery(sql10);
            while (rr2.next()) {
                String nomor = rr2.getString("id_tweet");
                String tweet = rr2.getString("tweet");
                String anotasi = rr2.getString("anotasi");
                String delims = "[ \t.,;()]+";
                StringBuilder builder = new StringBuilder();
                kata = tweet.trim().split(delims);
               // HitungTerm(kata);
                if (kata.length > 0) {
                    for (int i = 0; i < kata.length; i++) {
                        String tmpkata = kata[i];
                        if (!tmpkata.equals("")) {
                            String sql = "insert into TOKEN  (id_tweet,kata, anotator) values (?,?, ?)";
                            PreparedStatement o = (PreparedStatement) c10.prepareStatement(sql);
                            o.setString(1, nomor);
                            o.setString(2, tmpkata);
                            o.setString(3, anotasi);
                            o.executeUpdate();
                        }
                    }
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(TextProcessing.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void HitungTerm(String[] str) throws SQLException {
        double count = 0;
        String delims = "[ \t.,;()]+";
        ArrayList<String> wordsList = new ArrayList<String>();
        wordsList.addAll(Arrays.asList(str));
        String sql = "select * from kataemosi ";
        // where kata ='"+ str +"'
        Statement st = koneksi.getKoneksi().createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            String hsl = rs.getString("kata");
            // System.out.println(hsl);
            for (int i = 0; i < wordsList.size(); i++) {
                if (hsl.equals(wordsList.get(i))) {
                    count++;
                    System.out.println(wordsList.get(i) + "=" + count);
                }
            }
            //System.out.println(hsl + "=" + count);
        }
//                builder.append(wordsList);
    }

    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextProcessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextProcessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextProcessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextProcessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextProcessing().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonKataEmosi;
    private javax.swing.JButton jButtonNormalisasi;
    private javax.swing.JButton jButtonPraprocess;
    private javax.swing.JButton jButtonStopword;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
